2024-12-20 04:57:29,401 ERROR: Exception on /projects [GET] [in C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PythonII\TheZSolutions\app\routes\main.py", line 33, in projects
    return render_template('main/projects.html',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "F:\PythonII\TheZSolutions\app\templates\main\projects.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "F:\PythonII\TheZSolutions\app\templates\base.html", line 70, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PythonII\TheZSolutions\app\templates\main\projects.html", line 68, in block 'content'
    <a href="{{ url_for('main.project_detail', project_id=project.id) }}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.project_detail' with values ['project_id']. Did you mean 'main.projects' instead?
2024-12-20 05:03:24,617 INFO: The Z Solutions startup [in F:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:04:52,432 ERROR: Exception on /team [GET] [in C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PythonII\TheZSolutions\app\routes\main.py", line 42, in team
    return render_template('main/team.html', title='Our Team')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muhammad.ziada\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main/team.html
2024-12-20 05:06:44,918 INFO: The Z Solutions startup [in F:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:13:36,372 INFO: The Z Solutions startup [in f:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:14:25,380 INFO: The Z Solutions startup [in F:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:20:06,407 INFO: The Z Solutions startup [in F:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:33:35,380 INFO: The Z Solutions startup [in F:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:40:04,574 INFO: The Z Solutions startup [in f:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:43:41,817 INFO: The Z Solutions startup [in f:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:43:41,935 INFO: Created checkpoints directory [in f:\PythonII\TheZSolutions\run.py:14]
2024-12-20 05:43:41,936 INFO: Created uploads directory [in f:\PythonII\TheZSolutions\run.py:14]
2024-12-20 05:43:43,060 INFO: The Z Solutions startup [in f:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:44:20,761 INFO: The Z Solutions startup [in F:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:45:51,498 INFO: The Z Solutions startup [in f:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:46:33,262 INFO: The Z Solutions startup [in F:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:47:01,876 INFO: The Z Solutions startup [in f:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:48:14,345 INFO: The Z Solutions startup [in F:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:52:01,746 INFO: The Z Solutions startup [in f:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:55:20,443 INFO: The Z Solutions startup [in f:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:55:21,735 INFO: The Z Solutions startup [in f:\PythonII\TheZSolutions\app\__init__.py:41]
2024-12-20 05:58:45,600 INFO: The Z Solutions startup [in F:\PythonII\TheZSolutions\app\__init__.py:41]
